[package]
name = "rs-rigger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bastion = "0.4.5"
#rs-rigger-trait = {path = "../rs-rigger-trait"}
rs-rigger-derive = {path = "../rs-rigger-derive"}
